# Generated by Django 4.2.2 on 2023-06-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily_Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "Daily_Sales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("item_id", models.IntegerField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=20, unique=True)),
                ("price", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Monthly_Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "Monthly_Sales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("total_price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("shelf_no", models.CharField(blank=True, max_length=2, null=True)),
                ("shelf_floor", models.IntegerField(blank=True, null=True)),
                ("item_oreder", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_id", models.AutoField(primary_key=True, serialize=False)),
                ("store_name", models.CharField(max_length=45, unique=True)),
                ("located", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "store",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetailSale",
            fields=[
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="BLC.sales",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("unit_price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "detail_sale",
                "managed": False,
            },
        ),
    ]
